### ISSUE TITLE
Device in AAD but not enrolling into Intune

### ISSUE THREAD

**Issue by brettly80** [groovemaster17/IntuneMigration#1]
I'm having an issue where the device applies the provisioning package, the device shows in AAD, but it does not enroll in Intune, set primary user, etc. The device is not in Tenant A Autopilot before migration. It removes the device from tenant A. I've attached my post-migration log; I've removed any identifying information and the Robocopy info. I'm struggling to figure out why it's not working. Any help would be appreciated.
[post-migration.log](https://github.com/groovemaster17/IntuneMigration/files/12465011/post-migration.log)

**Comment by groovemaster17** [comment]
Hi @brettly80 - going through the log now- looks like the trouble starts when performing look ups against the "Tenant B" graph- when you log into https://intune.microsoft.com and navigate to Devices -> Windows -> Windows enrollment -> automatic enrollment, what is your scope set to?  Is it a specific group or all users?

**Comment by brettly80** [comment]
It's set to specific groups, I created a dynamic device group to include devices with the naming convention I set in the provisioning package.

Sent from Samsung Galaxy smartphone.
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brettly80** [comment]
Specific groups, the account I'm testing with is included in one of those groups.

**Comment by groovemaster17** [comment]
That's most likely the issue- since the provisioning package is the entity performing the enrollment, it is joining azure ad but not Intune.  I usually recommend setting the scope to "All", while mitigating risk with the following methods: https://www.getrubix.com/blog/automatic-enrollment-dont-be-afraid
You could try adding the provisioning package user the scoped group, since it will be visible in Azure AD users, but I have not tested that.

**Comment by brettly80** [comment]
Thanks for the insight, I'll give both a try.

**Comment by groovemaster17** [comment]
No problem, please keep me posted on your progress.

**Comment by brettly80** [comment]
So, I've gotten a bit farther. Adding the provisioning package user to the group, did nothing. I turned on enrollment for All, still doesn't register with Intune but this time it did add it to Autopilot. When I turned it on for All, I waited for about 5-10 minutes then ran the app, should I give it more time to propagate on the backend?

[migration.log](https://github.com/groovemaster17/IntuneMigration/files/12479870/migration.log)

[post-migration.log](https://github.com/groovemaster17/IntuneMigration/files/12479872/post-migration.log)

**Comment by brettly80** [comment]
> So, I've gotten a bit farther. Adding the provisioning package user to the group, did nothing. I turned on enrollment for All, still doesn't register with Intune but this time it did add it to Autopilot. When I turned it on for All, I waited for about 5-10 minutes then ran the app, should I give it more time to propagate on the backend?

I ran the scripts against a demo tenant that I have, and it worked perfectly, so it must be something in the other tenant that's holding it up. I will enable Auto enrollment for All let it sit for 24 hrs and try it again.

**Comment by groovemaster17** [comment]
Sounds good. Sometimes with Intune, things just need time to start running correctly. 

Glad to hear everything ran in the demo tenant. Let me know what happens with the waiting period.

**Comment by groovemaster17** [comment]
Going to assume this was a tenant issue.  If you have additional problems, let me know.
